"""
ProviderIntelligence — AI-derived provider profile for the discovery engine.

Three-layer intelligence model:
  1. Structured  — objective facts (name, services, hours, location)
  2. Contextual  — semi-objective (specialties, price tier, target audience)
  3. Identity    — subjective vibe & aesthetic (style, energy, brand personality)

The raw scan data flows through the intelligence pipeline, which extracts
vibe dimensions via GPT-4o Vision (Instagram images) and GPT-4o-mini
(text analysis). Providers confirm or adjust the AI suggestions during
onboarding (StepVibeConfirm), which becomes their canonical profile.
"""

import uuid
from datetime import datetime, timezone

from sqlalchemy import String, Integer, Float, Boolean, DateTime, Text, ForeignKey
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.db.session import Base

# ── Vibe taxonomy ─────────────────────────────────────────────────────────────
# Each tag belongs to a dimension. Providers can have 1-3 tags per dimension.
VIBE_DIMENSIONS = {
    "aesthetic": [
        "minimalist", "maximalist", "editorial", "boho", "classic",
        "avant-garde", "natural", "glamorous", "industrial", "vintage",
    ],
    "energy": [
        "calm", "energetic", "luxurious", "cozy", "edgy",
        "playful", "sophisticated", "zen", "bold", "intimate",
    ],
    "style_era": [
        "modern", "retro", "timeless", "trendsetting", "traditional",
    ],
    "brand_personality": [
        "artistic", "clinical", "boutique", "eco-conscious", "tech-forward",
        "family-friendly", "exclusive", "community-driven",
    ],
}

ALL_VIBE_TAGS = [tag for tags in VIBE_DIMENSIONS.values() for tag in tags]


class ProviderIntelligence(Base):
    __tablename__ = "provider_intelligence"

    id: Mapped[str] = mapped_column(
        String(36), primary_key=True, default=lambda: str(uuid.uuid4())
    )
    provider_id: Mapped[str] = mapped_column(
        String(36), ForeignKey("providers.provider_id"), nullable=False, unique=True, index=True
    )

    # ── Layer 1: Structured (stored on Provider model, referenced here) ───────
    # We don't duplicate structured data — it lives on the provider + services.

    # ── Layer 2: Contextual (semi-objective, AI-derived) ──────────────────────
    specialties: Mapped[str | None] = mapped_column(Text, nullable=True)        # JSON array of strings
    price_tier: Mapped[str | None] = mapped_column(String(20), nullable=True)   # budget|mid-range|premium|luxury
    target_audience: Mapped[str | None] = mapped_column(String(200), nullable=True)
    unique_value: Mapped[str | None] = mapped_column(Text, nullable=True)       # max 300 chars
    social_proof: Mapped[str | None] = mapped_column(Text, nullable=True)       # JSON array of quote strings

    # ── Layer 3: Identity / Vibe (subjective, AI-suggested) ───────────────────
    # AI-suggested vibe tags — JSON array of strings from VIBE_DIMENSIONS
    ai_vibe_tags: Mapped[str | None] = mapped_column(Text, nullable=True)
    # Provider-confirmed vibe tags — becomes canonical after onboarding
    confirmed_vibe_tags: Mapped[str | None] = mapped_column(Text, nullable=True)
    # Vibe confidence scores per dimension — JSON object {dimension: {tag: 0.0-1.0}}
    vibe_scores: Mapped[str | None] = mapped_column(Text, nullable=True)
    # Free-text vibe summary generated by AI
    vibe_summary: Mapped[str | None] = mapped_column(Text, nullable=True)

    # ── Source tracking ───────────────────────────────────────────────────────
    source_url: Mapped[str | None] = mapped_column(String(500), nullable=True)
    ig_posts_analyzed: Mapped[int] = mapped_column(Integer, default=0)
    # JSON array of source descriptors: [{type, url, analyzed_at}]
    data_sources: Mapped[str | None] = mapped_column(Text, nullable=True)

    # ── Processing status ─────────────────────────────────────────────────────
    # pending → analyzed → confirmed (by provider)
    status: Mapped[str] = mapped_column(String(20), default="pending", nullable=False)
    analyzed_at: Mapped[datetime | None] = mapped_column(DateTime, nullable=True)
    confirmed_at: Mapped[datetime | None] = mapped_column(DateTime, nullable=True)

    created_at: Mapped[datetime] = mapped_column(
        DateTime, default=lambda: datetime.now(timezone.utc)
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime,
        default=lambda: datetime.now(timezone.utc),
        onupdate=lambda: datetime.now(timezone.utc),
    )

    # Relationship
    provider: Mapped["Provider"] = relationship("Provider", backref="intelligence")  # noqa: F821
